//
//  MediaDetailsPresenterTests.swift
//  iTunesApp
//
//  Created by Vineet Sansare on 23/12/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import iTunesApp
import Quick
import Nimble

class MediaDetailsPresenterTests: QuickSpec {
    
    override func spec() {
        describe("MediaDetailsPresenter Tests") {
            
            // MARK: Subject under test
            var sut: MediaDetailsPresenter!
            var spy: MediaDetailsPresenterSpy!
            
            beforeSuite {
                setupLaunchesPresenter()
            }
            
            // MARK: Test setup
            func setupLaunchesPresenter() {
                sut = MediaDetailsPresenter()
            }
            
            // MARK: Test doubles
            class MediaDetailsPresenterSpy: MediaDetailsDisplayLogic {
                var displayInfoCalled = false
                
                func displayInfo(viewModel: MediaResponseModel) {
                    displayInfoCalled = true
                }
            }
            
            // MARK: Tests
            context("when view is loaded") {
                beforeEach {
                    spy = MediaDetailsPresenterSpy()
                    sut.viewController = spy
                    let media = SearchResult.stub()?.results?.first!
                    sut.present(item: media!)
                }
                it("should display updated mediaTypes") {
                    expect(spy.displayInfoCalled).to(beTrue())
                }
            }
        }
    }
}
