//
//  MediaTypeSelectorRouter.swift
//  iTunesApp
//
//  Created by Vineet Sansare on 17/12/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MediaTypeSelectorRoutingLogic {
    func routeToSearchCriteria()
}

protocol MediaTypeSelectorDataPassing {
  var dataStore: MediaTypeSelectorDataStore? { get set }
}

class MediaTypeSelectorRouter: NSObject, MediaTypeSelectorRoutingLogic, MediaTypeSelectorDataPassing {

  weak var viewController: MediaTypeSelectorViewController?
  var dataStore: MediaTypeSelectorDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

    func routeToSearchCriteria() {
        guard let source = viewController,
              let destination = viewController?.presentingViewController as? SearchCriteriaViewController else {
            return
        }
        var destinationDS = destination.router!.dataStore!
        passDataToSearchCriteria(source: dataStore!, destination: &destinationDS)
        navigateToSearchCriteriaScreen(source: source, destination: destination)
    }
  // MARK: Navigation
  func navigateToSearchCriteriaScreen(source: MediaTypeSelectorViewController, destination: SearchCriteriaViewController) {
    source.dismiss(animated: true, completion: nil)
  }
  
  // MARK: Passing data  
  func passDataToSearchCriteria(source: MediaTypeSelectorDataStore, destination: inout SearchCriteriaDataStore) {
    destination.mediaTypes = source.mediaTypes
  }
}
