//
//  MediaTypeSelectorPresenter.swift
//  iTunesApp
//
//  Created by Vineet Sansare on 17/12/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MediaTypeSelectorPresentationLogic {
    func presentTellSearchCriteria(response: MediaTypeSelector.MediaType.Response)
}

class MediaTypeSelectorPresenter: MediaTypeSelectorPresentationLogic {
    weak var viewController: MediaTypeSelectorDisplayLogic?
    
    // MARK: Do something
    func presentTellSearchCriteria(response: MediaTypeSelector.MediaType.Response) {
        let viewModel = MediaTypeSelector.MediaType.ViewModel(mediaTypes: response.mediaTypes)
        viewController?.displaySomething(viewModel: viewModel)
    }
}
