//
//  MediaTypeSelectorInteractor.swift
//  iTunesApp
//
//  Created by Vineet Sansare on 17/12/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MediaTypeSelectorBusinessLogic {
    func updateWithSelectedMedia(request: MediaTypeSelector.MediaType.Request)
    
    func displaySearchCriteria(request: MediaTypeSelector.MediaType.Request)
}

protocol MediaTypeSelectorDataStore {
  var mediaTypes: [String] { get set }
}

class MediaTypeSelectorInteractor: MediaTypeSelectorBusinessLogic, MediaTypeSelectorDataStore {
    var mediaTypes: [String] = []
    
    var presenter: MediaTypeSelectorPresentationLogic?
    var worker: MediaTypeSelectorWorker?
    
    // MARK: Do something
    
    func updateWithSelectedMedia(request: MediaTypeSelector.MediaType.Request) {
        let response = MediaTypeSelector.MediaType.Response(mediaTypes: request.mediaTypes)
        mediaTypes = request.mediaTypes
        presenter?.presentUpdatedMediaTypes(response: response)
    }
    
    func displaySearchCriteria(request: MediaTypeSelector.MediaType.Request) {
        let response = MediaTypeSelector.MediaType.Response(mediaTypes: request.mediaTypes)
        mediaTypes = request.mediaTypes
        presenter?.presentSearchCriteria(response: response)
    }
}
