//
//  MediaDetailsInteractor.swift
//  iTunesApp
//
//  Created by Vineet Sansare on 18/12/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MediaDetailsBusinessLogic {
    func updateDetail()
}

protocol MediaDetailsDataStore {
    var itemDetail: MediaResponseModel! { get set }
}

class MediaDetailsInteractor: MediaDetailsBusinessLogic, MediaDetailsDataStore {
    var itemDetail: MediaResponseModel!
    var presenter: MediaDetailsPresentationLogic?
    var worker: MediaDetailsWorker?
 
    func updateDetail() {
        presenter?.present(item: itemDetail)
    }
}
