//
//  MediaDetailsRouter.swift
//  iTunesApp
//
//  Created by Vineet Sansare on 18/12/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MediaDetailsRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol MediaDetailsDataPassing {
    var dataStore: MediaDetailsDataStore? { get }
}

class MediaDetailsRouter: NSObject, MediaDetailsRoutingLogic, MediaDetailsDataPassing {
    weak var viewController: MediaDetailsViewController?
    var dataStore: MediaDetailsDataStore?
}
