//
//  SearchResultsInteractor.swift
//  iTunesApp
//
//  Created by Vineet Sansare on 17/12/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchResultsBusinessLogic {
    func updateMedia()
}

protocol SearchResultsDataStore {
    var searchedItems: [[MediaResponseModel]] { get set }
    var types: [String] { get set }
}

class SearchResultsInteractor: SearchResultsBusinessLogic, SearchResultsDataStore {
    var searchedItems: [[MediaResponseModel]] = []
    var types: [String] = []
    var presenter: SearchResultsPresentationLogic?
    var worker: SearchResultsWorker?
    
    func updateMedia() {
        presenter?.showResult(items: searchedItems, types: types)
    }    
}
