//
//  SearchResultsRouter.swift
//  iTunesApp
//
//  Created by Vineet Sansare on 17/12/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchResultsRoutingLogic {
    func routeToDetail(with data: MediaResponseModel)
}

protocol SearchResultsDataPassing {
    var dataStore: SearchResultsDataStore? { get }
    func passDataToDetail(source: MediaResponseModel, destination: inout MediaDetailsDataStore)
}

class SearchResultsRouter: NSObject, SearchResultsRoutingLogic, SearchResultsDataPassing {
        
  weak var viewController: SearchResultsViewController?
  var dataStore: SearchResultsDataStore?
  
  // MARK: Routing
    func routeToDetail(with data: MediaResponseModel) {        
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        guard let searchResultsVC = storyboard.instantiateViewController(withIdentifier: MediaDetailsViewController.identifier) as? MediaDetailsViewController else {
            return
        }
        if var movieDetailDS = searchResultsVC.router?.dataStore {
            passDataToDetail(source: data, destination: &movieDetailDS)
        }
        navigateToSearchResults(source: viewController!, destination: searchResultsVC)
    }
    
    func passDataToDetail(source: MediaResponseModel, destination: inout MediaDetailsDataStore) {
        destination.itemDetail = source
    }
    
    func navigateToSearchResults(source: SearchResultsViewController, destination: MediaDetailsViewController) {
        source.show(destination, sender: nil)
    }
}
