//
//  SearchCriteriaModels.swift
//  iTunesApp
//
//  Created by Vineet Sansare on 17/12/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SearchCriteria {
    
    // MARK: Use cases
    enum Entity { // Can be music, movie, podcast
        struct Request {
            var term: String?
            var entities: [String]?
        }
        struct Response {
            var media: [[MediaResponseModel]]
            var types: [String]
        }
        struct ViewModel {
            var media: [[MediaResponseModel]]
            var types: [String]
        }
    }
    
    enum SelectedEntity { // Can be music, movie, podcast
        struct Request {
            
        }
        struct Response {
            var types: [String]
        }
        struct ViewModel {
            var types: [String]
        }
    }
}
