//
//  SearchCriteriaPresenter.swift
//  iTunesApp
//
//  Created by Vineet Sansare on 17/12/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchCriteriaPresentationLogic {
    func presentResultScreenWith(response: SearchCriteria.Entity.Response)
    func presentError(message: String)
    
    func presentMediaTypeSelector(response: SearchCriteria.SelectedEntity.Response)
}

class SearchCriteriaPresenter: SearchCriteriaPresentationLogic {
    weak var viewController: SearchCriteriaDisplayLogic?
    
    func presentResultScreenWith(response: SearchCriteria.Entity.Response) {
        let searchCriteriaViewModel = SearchCriteria.Entity.ViewModel(media: response.media, types: response.types)
        viewController?.showResultScreenWith(viewModel: searchCriteriaViewModel)
    }
    
    func presentError(message: String) {
        viewController?.showError(message: message)
    }
    
    func presentMediaTypeSelector(response: SearchCriteria.SelectedEntity.Response) {
        viewController?.showMediaTypeSelectorWith(viewModel: SearchCriteria.SelectedEntity.ViewModel(types: response.types))
    }
}
