//
//  SearchCriteriaWorkerTests.swift
//  iTunesApp
//
//  Created by Vineet Sansare on 21/12/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import iTunesApp
import XCTest

class SearchCriteriaWorkerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: SearchCriteriaWorker!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupSearchCriteriaWorker()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupSearchCriteriaWorker()
  {
    sut = SearchCriteriaWorker()
  }
  
  // MARK: Test doubles
  
  // MARK: Tests
  
  func testSomething()
  {
    // Given
    
    // When
    
    // Then
  }
}
